In [12]:
import numpy as np
per1 = np.array([[0,0,0,0],
                 [0,1,1,1],
                 [0,1,1,1],
                 [0,1,1,1]])
per2 = np.array([[1,0,1,1],
                 [0,0,0,0],
                 [1,0,1,1],
                 [1,0,1,1]])
per3 = np.array([[1,1,0,1],
                 [1,1,0,1],
                 [0,0,0,0],
                 [1,1,0,1]])
per4 = np.array([[1,1,1,0],
                 [1,1,1,0],
                 [1,1,1,0],
                 [0,0,0,0]])
a = np.array([[0.20, 0.01, 0.01, 0.01],
              [0.15, 0.01, 0.01, 0.02],
              [0.01, 0.01, 0.01, 0.14],
              [0.01, 0.01, 0.01, 0.01]])

In [17]:
map1 = np.full((4,4), np.mean(a*per1))
map2 = np.full((4,4), np.mean(a*per2))
map3 = np.full((4,4), np.mean(a*per3))
map4 = np.full((4,4), np.mean(a*per4))

In [23]:
map1*per1

array([[0.02625, 0.02625, 0.02625, 0.     ],
       [0.02625, 0.02625, 0.02625, 0.     ],
       [0.02625, 0.02625, 0.02625, 0.     ],
       [0.     , 0.     , 0.     , 0.     ]])

In [24]:
map2*per2

array([[0.025625, 0.      , 0.025625, 0.025625],
       [0.      , 0.      , 0.      , 0.      ],
       [0.025625, 0.      , 0.025625, 0.025625],
       [0.025625, 0.      , 0.025625, 0.025625]])

In [25]:
map3*per3

array([[0.026875, 0.026875, 0.      , 0.026875],
       [0.026875, 0.026875, 0.      , 0.026875],
       [0.      , 0.      , 0.      , 0.      ],
       [0.026875, 0.026875, 0.      , 0.026875]])

In [26]:
map4*per4

array([[0.02625, 0.02625, 0.02625, 0.     ],
       [0.02625, 0.02625, 0.02625, 0.     ],
       [0.02625, 0.02625, 0.02625, 0.     ],
       [0.     , 0.     , 0.     , 0.     ]])

In [22]:
map1*per1 + map2*per2 + map3*per3 + map4*per4

array([[0.07875 , 0.053125, 0.051875, 0.0525  ],
       [0.053125, 0.0675  , 0.040625, 0.04125 ],
       [0.051875, 0.040625, 0.06625 , 0.04    ],
       [0.0525  , 0.04125 , 0.04    , 0.066875]])