In [1]:
import cv2
import numpy as np

In [2]:
activation = np.array([ [1,1,1,1,1,1,1],
                        [1,1,1,1,1,1,1],
                        [1,1,1,1,1,1,2],
                        [1,5,4,1,5,1,1],
                        [1,3,2,1,1,1,1],
                        [1,1,1,1,1,1,1],
                        [1,1,1,1,1,1,1]], dtype=np.uint8)
gradient = np.array([   [1,1,1,1,1,1,1],
                        [1,1,1,1,1,1,1],
                        [1,1,1,1,1,1,2],
                        [1,1,1,1,3,1,1],
                        [1,5,1,1,1,1,1],
                        [1,1,1,1,1,1,1],
                        [1,1,1,1,1,1,1]], dtype=np.uint8)
activation = np.expand_dims(activation, axis=-1)
gradient = np.expand_dims(gradient, axis=-1)
target_size = (14,14)

In [3]:
activation_up = cv2.resize(activation, target_size)
gradient_up = cv2.resize(gradient, target_size)

In [4]:
activation_up

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2],
       [1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2],
       [1, 2, 3, 4, 3, 3, 2, 2, 3, 3, 2, 1, 1, 1],
       [1, 2, 4, 4, 4, 3, 2, 2, 3, 3, 2, 1, 1, 1],
       [1, 2, 3, 3, 3, 2, 1, 1, 2, 2, 1, 1, 1, 1],
       [1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [5]:
gradient_up

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2],
       [1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1],
       [1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1],
       [1, 2, 3, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 2, 3, 3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [6]:
total = activation_up * gradient_up
total

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 4],
       [1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 4, 4],
       [1, 2, 3, 4, 3, 3, 2, 2, 6, 6, 2, 1, 1, 1],
       [1, 2, 8, 8, 4, 3, 2, 2, 6, 6, 2, 1, 1, 1],
       [1, 4, 9, 9, 6, 2, 1, 1, 2, 2, 1, 1, 1, 1],
       [1, 2, 6, 6, 4, 2, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=uint8)

In [7]:
total = cv2.resize(activation * gradient, target_size)
total

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  3,  3],
       [ 1,  1,  2,  2,  2,  2,  1,  2,  4,  4,  2,  2,  3,  3],
       [ 1,  2,  3,  4,  3,  3,  2,  4,  9,  9,  4,  1,  2,  2],
       [ 1,  3,  6,  6,  4,  3,  2,  4,  9,  9,  4,  1,  1,  1],
       [ 1,  4, 10, 10,  5,  2,  1,  2,  4,  4,  2,  1,  1,  1],
       [ 1,  4,  9,  9,  4,  2,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  2,  4,  4,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1]],
      dtype=uint8)